[theme]
primaryColor = "#6366F1"
backgroundColor = "#090D16"
secondaryBackgroundColor = "#121829"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
